### ISSUE TITLE
`import` and `using` are not equivalent

### ISSUE THREAD

**Issue by simonp0420** [RoyiAvital/Julia100Exercises#1]
The two solutions given for Question 001 are not equivalent, as claimed.  The first solution (employing `import`) requires prefixing exported module function names with `LA.` while the second (employing `using`) doesn't.  Even if the second solution were changed to 
```
import LinearAlgebra
const LA = LinearAlgebra
```
it wouldn't be precisely equivalent to the first because the module names would also be available by prefixing either with `LinearAlgebra.` or `LA.` while in the first solution they are only available by prefixing with `LA.`

**Comment by RoyiAvital** [comment]
Fixed with https://github.com/RoyiAvital/Julia100Exercises/commit/d14f4a1b590ed2397ad9d9b2408076665146ee18.
